apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
      - name: tic-tac-toe
        image: 045555583762.dkr.ecr.ap-south-2.amazonaws.com/go-web-app:c3e5e25e26a55ac5b8e466f49f695954eec24d84
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: ecr-regcred
